mysite/BestBuySearch/urls.py
from django.shortcuts import render

from django.urls import path

from . import views

# Create your urls here.

app_name = 'BestBuySearch'

urlpatterns = [
         #ex: /BestBuySearch/
         #path('', views.IndexView.as_view(), name='index'),
         #path('products/', views.ProductView.as_view(), name = "products"),
         
         #basic homepage + details:
         path('products/', views.ProductView.as_view(), name = "products"),
         path('products/<int:pk>/product_details/', views.ProductDetailsView.as_view(), name = "product_details"),
         #signups:
         path("customer_signup/", views.CustomerSignUpView.as_view(), name = "customer_signup"),
         path("vendor_signup/", views.VendorSignUpView.as_view(), name = "vendor_signup"),
         #search results:
         path('products/similar_search/', views.SimilarResultsView.as_view(), name = "similar_results"),
         path('products/exact_search/', views.ExactResultsView.as_view(), name = "exact_results"),
         path('products/requirement_search/MultipleSearch/', views.MultipleSearch, name = "MultipleSearch"),
            #path('products/requirement_search/<str:name>/<int:cost>/<int:category>/<int:payment_type>/', views.myfunct, name = "myfunct"),
         #product editing:
         path('products/add_product/', views.ProductCreateView.as_view(), name = 'add_product'),
         path('products/all_products/', views.ThisVendorsProductsView.as_view(), name = 'all_products'),
         path('products/all_products/<int:pk>/update/', views.ProductUpdateView.as_view(), name = 'update_product'),
         path('products/all_products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name = 'delete_product'),
         #cart urls:
         path('products/checkout/', views.Cart.as_view(), name = 'checkout'),
         path('products/<int:pk>/add_to_cart/', views.add_to_cart, name = 'add_to_cart'),
         path('products/checkout/<int:pk>/rm_from_cart/', views.rm_from_cart, name = 'rm_from_cart'),
         path('products/recommendations/', views.RecommendsView.as_view(), name = "recommends"),
         
         #polls:
         #ex: /BestBuySearch/5/
         #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
         #ex: /BestBuySearch/5/results/
         #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
         #ex: /BestBuySearch/5/vote/
         #path('<int:question_id>/vote/', views.vote, name='vote')
       ]

mysite/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.conf.urls.static import static

urlpatterns = [
    #path('polls/', include('polls.urls')),
    path('BestBuySearch/', include('BestBuySearch.urls')), 
    #path('', include('BestBuySearch.urls')), #also map reg request to this app, not gud to hardcode
    path('admin/', admin.site.urls),
    #path('accounts/', include('BestBuySearch.urls')), #just incase
    path("BestBuySearch/", include("django.contrib.auth.urls"))
    #path("", TemplateView.as_view(template_name = "home.html"), name = "home")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #needed to set media url and root for image retrieval

mysite/BestBuySearch/models.py
import datetime
from secrets import choice
from unicodedata import category
from unittest.util import _MAX_LENGTH

from django.db import models
from django.utils import timezone

from django.contrib import admin
from django.contrib.auth.models import AbstractUser
#from django.contrib.auth.models import User

from django.urls import reverse

from django.core.validators import MinValueValidator
from decimal import *

# Create your models here.

#query model

"""
class RequirementsQuerySet(models.QuerySet):
    def search(self, **kwargs):
        qs = self
        if kwargs.get('q', ''):
            qs = qs.filter(name__iexact=kwargs['q'])
        if kwargs.get('government_type', []):
            qs = qs.filter(government_type=kwargs['government_type'])
        if kwargs.get('industry', []):
            qs = qs.filter(industry=kwargs['industry'])
        return qs
"""

#User model

class User(AbstractUser):
    """
    Add more fields to default Django User table.
    Adds extra fields common to all users.
    """
    is_vendor = models.BooleanField(default = False)
    is_customer = models.BooleanField(default = False)

#product model

class VendorProduct(models.Model):
    """Item created by vendors and purchased by clients."""
    #VID = models.ForeignKey(Vendor, on_delete = models.CASCADE)
    PID = models.BigAutoField(primary_key = True)
    cost = models.DecimalField(default = 0, max_digits = 20, decimal_places = 2, validators=[MinValueValidator( Decimal('0.00'))] )
    name = models.CharField(max_length = 200)

    #category
    TV_HOME_THEATER = 1
    AUDIO = 2
    MUSICAL_INSTRUMENTS = 3
    CAR_ELECTRONICS_GPS = 4
    CAMERAS_CAMCORDERS_DRONES = 5
    COMPUTERS_TABLETS = 6
    MOVIES_MUSIC = 7
    VIDEO_GAMES = 8
    CELL_PHONES = 9
    APPLIANCES = 10
    GIFT_CARDS = 11
    NAME_BRANDS = 12
    BABY_CARE = 13
    SERVICES = 14
    HEALTH_WELLNESS = 15
    TOYS_GAMES_COLLECTABLES = 16
    SMART_HOME = 17
    SPORTS_FITNESS_RECREATION = 18
    HOME_FURNITURE_OFFICE = 19
    WEARABLE_TECHNOLOGY = 20
    CATEGORY = (
        (TV_HOME_THEATER, "TV & Home Theater"),
        (AUDIO, "Audio"),
        (MUSICAL_INSTRUMENTS, "Musical Instruments" ),
        (CAR_ELECTRONICS_GPS, "Car, Electronics & GPS"),
        (CAMERAS_CAMCORDERS_DRONES, "Cameras, Camcorders & Drone"),
        (COMPUTERS_TABLETS, "Computers & Tablets"),
        (MOVIES_MUSIC, "Movies & Music"),
        (VIDEO_GAMES, "Video Games"),
        (CELL_PHONES, "Cell Phones"),
        (APPLIANCES, "Appliances"),
        (GIFT_CARDS, "Gift Cards"),
        (NAME_BRANDS, "Name Brands"),
        (BABY_CARE, "Baby Care"),
        (SERVICES, "Services"),
        (HEALTH_WELLNESS, "Health & Wellness"),
        (TOYS_GAMES_COLLECTABLES, "Toys, Games & Collectibles"),
        (SMART_HOME, "Smart Home"),
        (SPORTS_FITNESS_RECREATION, "Sports, Fitness & Recreation"),
        (HOME_FURNITURE_OFFICE, "Home, Furniture & Office"),
        (WEARABLE_TECHNOLOGY, "Wearable Technology"),
    )
    category = models.PositiveSmallIntegerField(choices=CATEGORY)
    
    #payment type
    IN_FULL = 1
    MONTHLY = 2
    ANNUALLY = 3
    PAYMENT_TYPE = (
        (IN_FULL, 'one time payment'),
        (MONTHLY, 'monthly'),
        (ANNUALLY, 'annually'),
    )
    payment_type = models.PositiveSmallIntegerField( choices=PAYMENT_TYPE)

    quantity = models.PositiveBigIntegerField(default=1) #, validators=[MinValueValidator( [('1')])

    #description fields:
    product_description = models.CharField(max_length=200, default='product description...')
    brief_description = models.CharField(max_length=20, default='brief description...')

    #display images (auto uploads to media folder)
        #WIDTH_REQ = 600
        #HEIGHT_REQ = 700
        #small_display_image = models.ImageField(upload_to='images/', width_field=450, height_field=300, max_length=100)
        #big_display_image = models.ImageField(upload_to='images/', width_field=WIDTH_REQ, height_field=HEIGHT_REQ, max_length=100)
    small_display_image = models.ImageField(upload_to='images/', max_length=500)
    big_display_image = models.ImageField(upload_to='images/', max_length=500) 
        #no idea how to restrict the upload resolution

    #dates:
    update_date = models.DateTimeField("date updated")
    pub_date = models.DateTimeField("date published")

    #should include full description field + short description field
    
    created_by = models.ForeignKey(User, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        """Used by CreateView and UpdateView as success_url."""
        #return reverse('add_product', kwargs = {'pk': self.pk})
        return reverse('BestBuySearch:products')
    
#User models

class Customer(models.Model):
    """
    Create profile model via 1-to-1 relations to user model.
    """
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    products = models.ManyToManyField(VendorProduct)
    
    
class Vendor(models.Model):
    """
    Create profile model via 1-to-1 relations to user model.
    """
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    brand = models.CharField(max_length = 200)

"""#polls models
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    #needs placed right above function:
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    
    #second ed:
    def was_published_recently(self):
        nowTime = timezone.now()
        
        #ret true if pub_date is less than rn + larger than a day ago's date
        return (nowTime - datetime.timedelta(days=1)) <= self.pub_date <= nowTime
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
"""

mysite/BestBuySearch/forms.py
# -*- coding: utf-8 -*-

from django import forms

from django.contrib.auth.forms import UserCreationForm

from django.db import transaction

from .models import Vendor, User, Customer, VendorProduct
#from django.contrib.auth.models import User

class CustomerSignUpForm(UserCreationForm):
    Agree_Terms = forms.BooleanField(required=True, label="I agree to the Terms and Conditions")
    
    class Meta(UserCreationForm.Meta):
        """Signup redef'd user."""
        model = User
        
    @transaction.atomic
    def save(self, commit = True):
        """
            Atomically save user as customer.
            Can override to not commit save.
        """
        user = super().save(commit = False)
        user.is_customer = True
        if (commit):
            user.save()
        #create new customer: 
        customer = Customer.objects.create(user = user)
        return user
    
class VendorSignUpForm(UserCreationForm):
    """Add brand name field to default vendor sign up."""

    brand = forms.CharField(required = True, label="Brand Name")
    Agree_Terms = forms.BooleanField(required=True, label="I agree to the Terms and Conditions")
    
    class Meta(UserCreationForm.Meta):
        """Signup redef'd user."""
        model = User
        
    @transaction.atomic
    def save(self):
        """
            Atomically save user as vendor.
        """
        user = super().save(commit = False)
        user.is_vendor = True
        user.save()
        #make sure brand data saved by adding entry: 
        vendor = Vendor.objects.create(user = user, brand = self.cleaned_data['brand'])
        return user

class RequirementForm(forms.Form): #forms.ModelForm):
    """Form for requirements search."""
    #override cost input to be options
    ANY = 0
    LTE_50 = 50
    LTE_100 = 100
    LTE_500 = 500
    COST_CHOICES = (
        (ANY, "Any"),
        (LTE_50, "<= $50"),
        (LTE_100, "<= $100"),
        (LTE_500, "<= $500"),
    )
    cost = forms.ChoiceField(choices = COST_CHOICES)

    #add NONE field to default category search
    NONE = 0
    CATEGORY_CHOICES = (
        (NONE, "None"),
    ) + VendorProduct.CATEGORY
    category = forms.ChoiceField(choices=CATEGORY_CHOICES)

    #ordering
    PUB_DATE = 1
    RECENTLY_UPDATED = 2
    PRICE_ASC = 3
    PRICE_DESC = 4
    ORDERING_CHOICES = (
        (NONE, "None"),
        (PUB_DATE, "Published Date"),
        (RECENTLY_UPDATED, "Recently Updated"),
        (PRICE_ASC, "Price (Low to High)"),
        (PRICE_DESC, "Price (High to Low)"),
    )
    ordering = forms.ChoiceField(choices=ORDERING_CHOICES)
    
    #payment type (mapped from model choices)
    #payment_type = forms.ChoiceField(choices = VendorProduct.PAYMENT_TYPE)

    #add ANY field to default payment type search
    # specified as 0 above
    PAYMENT_CHOICES = (
        (ANY, "Any"),
    ) + VendorProduct.PAYMENT_TYPE
    payment_type = forms.ChoiceField(choices=PAYMENT_CHOICES)

    class Meta:
        model = VendorProduct
        fields = [ 'cost', 'ordering', 'category', 'payment_type']

mysite/BestBuySearch/templates/BestBuySearch/all_products.html
{% extends 'BestBuySearch/base_shop.html' %}

<!DOCTYPE html>

    <head>
        <!-- inherited -->

        {% block title %}
            {{ user.username }} Created Products
        {% endblock title %}

    </head>
    <body>
        <!-- Navigation-->
        
        <!-- Header-->


        <!-- Section-->
            {% block section_title %}
        		{% if user.is_vendor %}
            		<h2> Products created by {{ user.username }}</h2>
                {% else %}
                    <h2> All products </h2>
                {% endif %}
            {% endblock section_title %}
        		
            <!-- listings -->
            {% block listings %}
                {% if allproducts_list %}
                    {% for vendorproduct in allproducts_list %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Edit and delete -->     
                                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem"><a class="nav-link active" aria-current="page" href="{% url 'BestBuySearch:delete_product' vendorproduct.PID %}">Delete</a></div> 
                                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; left: 0.5rem"><a class="nav-link active" aria-current="page" href="{% url 'BestBuySearch:update_product' vendorproduct.PID %}">Edit</a></div>
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ vendorproduct.small_display_image.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ vendorproduct.name }}</h5>
                                        <!-- Product price-->
                                        ${{ vendorproduct.cost }}
                                        <li>category: {{ vendorproduct.get_category_display }}</li>
                                        
                                        <li>payment type: {{ vendorproduct.get_payment_type_display }}</li>
                                        <li>quantity: {{ vendorproduct.quantity }}</li>
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'BestBuySearch:product_details' vendorproduct.PID %}">View details</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No products are available.</p>
                {% endif %}
            {% endblock listings %}
        </section>
		
        <!-- Footer-->
 
    </body>
</html>

mysite/BestBuySearch/templates/BestBuySearch/base.html
{% load static %}

<!DOCTYPE html>

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Product matching service" />
        <meta name="author" content="Seth Cram" />
        
        <title>
        
            {% block title %}
                Home
            {% endblock title %}
            - BestBuySearch Shop 
        </title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'BestBuySearch/eCommerce/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'BestBuySearch/eCommerce/css/styles.css' %}" rel="stylesheet" />

        {% block more_styling %}
        
        {% endblock more_styling %}

    </head>
    <body class="d-flex flex-column min-vh-100">
        
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            {% block navbar %}
                <div class="container px-4 px-lg-5">
                    <a class="navbar-brand">BestBuySearch</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'BestBuySearch:products' %}">Home</a></li>                                                         
                            
                            <!-- Search Types -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Search Type</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'BestBuySearch:exact_results' %}">Exact Search</a></li>
                                    <li><a class="dropdown-item" href="{% url 'BestBuySearch:similar_results' %}">Similar Search</a></li>
                                    <li><a class="dropdown-item" href="{% url 'BestBuySearch:MultipleSearch' %}">Requirements Search</a></li>
                                </ul>   
                            </li>                           
                                            
                            {% if user.is_authenticated %}
                                {% if user.is_vendor %}
                                    <!-- Vendor Actions -->
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Vendor Action</a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li><a class="dropdown-item" href="{% url 'BestBuySearch:add_product' %}">Add New Item</a></li>
                                            <li><a class="dropdown-item" href="{% url 'BestBuySearch:all_products' %}">Edit/Delete Item</a></li>
                                        </ul>   
                                    </li>        							
                                
                                    
                                {% else %}

                                <li class="nav-item"><a class="nav-link" href="{% url 'BestBuySearch:recommends' %}">Recommendations</a></li> 
                                
                                <!-- cart -->
                                <form class="d-flex">
                                    <a class="nav-link" type = "submit" href="{% url 'BestBuySearch:checkout' %}">
                                        <i class="bi-cart-fill me-1"></i>
                                            Cart
                                        <span class="badge bg-dark text-white ms-1 rounded-pill"></span>
                                    </a>
                                </form>
                                {% endif %}	
                            {% endif %}
                                    
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>    						
                        </ul>
                        
                    </div>
                </div>
            {% endblock navbar %}
        </nav>
        
        <!-- inner body -->
        {% block inner-body %}
            <!-- header -->
            {% block header %}
                {% block search_bar %}

                {% endblock search_bar %}
                {% block options %}
                
                {% endblock options %}

            {% endblock header %}

            <!-- section -->
            {% block section %}
                {% block section_title %}
                    
                {% endblock section_title %}

                {% block listings %}

                {% endblock listings %}
            {% endblock section %}

        {% endblock inner-body %}
		
        {% block pagination %}
        
        {% endblock pagination %}


        {% block footer%}
            <!-- Footer-->
            <footer class="py-5 bg-dark">
                <div class="container"><p class="m-0 text-center text-white">Copyright &copy; BestBuySearch 2022</p></div>
                <ul class="list-inline text-center">
                    <li class="list-inline-item"><a>Privacy</a></li>
                    <li class="list-inline-item"><a target="_blank" href="https://www.termsfeed.com/live/0625eac9-112a-4887-a7e6-c2b88100937e">Terms</a></li>
                    <li class="list-inline-item"><a>Support</a></li>
                </ul>
            </footer>
        {% endblock footer%}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'BestBuySearch/eCommerce/js/scripts.js' %}"></script> 
    
        {% block more_footer %}
        
        {% endblock more_footer %}
    
    </body>
</html>

mysite/BestBuySearch/templates/BestBuySearch/detail.html
<!DOCTYPE html>
<html>

<!--Second Interation: -->
<form action="{% url 'BestBuySearch:vote' question.id %}" method="post"> 
{%csrf_token %}
<fieldset>
	<legend><h1>
		{{ question.question_text }}
	</h1></legend> <!-- legend = ? -->
	
	{% if error_meggase %}
		<p><strong>{{ error_message }}</strong></p>  <!-- strong = ? -->
	{% endif %}
	
	{% for choice in question.choice_set.all %}
	<!-- radio input is bulleted, sel'able points -->
		<input type="radio" name="choice" 
			id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		<label for="choice{{ forloop.counter }}">
			{{ choice.choice_text }}</label><br> <!-- br = ? -->
	{% endfor %}
</fieldset>

<input type="submit" value="Vote">

</form>	
		

</html>

mysite/BestBuySearch/templates/BestBuySearch/exact_results.html
{% extends 'BestBuySearch/base_shop.html' %}

<!DOCTYPE html>

    <head>
        <!-- inherited -->

        {% block title %}
            Exact Search
        {% endblock title %}


    </head>
    <body>
        <!-- Navbar should be inserted here -->

        <!-- Header should be inserted around search bar-->           
        {% block search_bar %}
            <!-- search bar -->
            <form action="{% url 'BestBuySearch:exact_results' %}" method="get">
            <input name="q" type="text" placeholder="Search name or category">
            </form>
        {% endblock search_bar %}

        
        <!-- Perfect match -->
        {% block section_title %}
            <h2> Exact Matches </h2>
        {% endblock section_title %}
        
        <!-- listings -->
        {% block listings %}
            {% if exactmatch_list %}
                {% for vendorproduct in exactmatch_list %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ vendorproduct.small_display_image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ vendorproduct.name }}</h5>
                                    <!-- Product price-->
                                    ${{ vendorproduct.cost }}
                                    <!-- Product pay type-->
                                    <p> {{ vendorproduct.get_payment_type_display }} </p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                {% if user.is_customer %}
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'BestBuySearch:add_to_cart' vendorproduct.PID %}">Add to cart</a></div>
                                {% endif %}
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'BestBuySearch:product_details' vendorproduct.PID %}">View details</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No products are available.</p>
            {% endif %}
        {% endblock listings %}
		
        <!-- footer should be inherited here -->

    </body>
</html>

mysite/BestBuySearch/templates/BestBuySearch/requirement_results.html
{% extends 'BestBuySearch/base_shop.html' %}

<!DOCTYPE html>

    <head>
       {% block title  %}
            Requirement Search
       {% endblock title %}
    </head>
    <body>
        <!-- Navigation-->
        
        <!-- Header-->

        {#{% block options %}#}
            <!-- dropdown button -->
            
            <div class="dropdown">
                <button data-bs-toggle="dropdown" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">
                    Dropdown button
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
            

            <!-- Price Radio -->
            
            <div class="form-check">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
            <label class="form-check-label" for="flexRadioDefault1">
                Default radio
            </label>
            </div>
            <div class="form-check">
            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
            <label class="form-check-label" for="flexRadioDefault2">
                Default checked radio
            </label>
            </div>
            

            <!-- Price Radio Toggle Btns -->
            
            <input type="radio" class="btn-check" name="options" id="option1" autocomplete="off" checked>
            <label class="btn btn-secondary" for="option1">Checked</label>

            <input type="radio" class="btn-check" name="options" id="option2" autocomplete="off">
            <label class="btn btn-secondary" for="option2">Radio</label>

            <input type="radio" class="btn-check" name="options" id="option3" autocomplete="off" disabled>
            <label class="btn btn-secondary" for="option3">Disabled</label>

            <input type="radio" class="btn-check" name="options" id="option4" autocomplete="off">
            <label class="btn btn-secondary" for="option4">Radio</label>
            

        {#{% endblock options %}#}


        <!-- Section-->
        
        {% block search_bar %}
            <form method="post" action = "{% url 'BestBuySearch:MultipleSearch' %}" >
                {% csrf_token %}
                {{ form.as_table }}

                <button type="submit">Search</button>
            </form>
        {% endblock search_bar %}

            <!-- title -->
            {% block section_title %}
                <h2> Requirement Matches </h2>
            {% endblock section_title %}

            <!-- requirements listings -->
            {% block listings %}
                {% if VendorProduct %}
                    {% for vendorproduct in page_obj %}
                    
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ vendorproduct.small_display_image.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ vendorproduct.name }}</h5>
                                        <!-- Product price-->
                                        ${{ vendorproduct.cost }}
                                        <!-- Product pay type-->
                                        <p> {{ vendorproduct.get_payment_type_display }} </p>
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    {% if user.is_customer %}
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'BestBuySearch:add_to_cart' vendorproduct.PID %}">Add to cart</a></div>
                                    {% endif %}
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'BestBuySearch:product_details' vendorproduct.PID %}">View details</a></div>
                                </div>
                            </div>
                        </div>
                    
                    {% endfor %}
                {% else %}
                    <p>No products are available.</p>
                {% endif %}
            {% endblock listings %}
        
            <!-- listings-->
		
        <!-- Footer-->
 
    </body>
</html>

mysite/BestBuySearch/templates/BestBuySearch/results.html
<!DOCTYPE html>
<html>
	<h1>{{ question.question_text }}</h1>
	
	<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} 
			vote{{ choice.votes|pluralize }} </li> <!-- "|pluralize" = ? combines them? -->
	{% endfor %}
	</ul>
	
	<!-- map inner text to requested url -->
	<a href="{% url 'BestBuySearch:detail' question.id %}">Vote again?</a>
</html>